### PR TITLE
Fixing image binary output

### PR DESCRIPTION
**Pull request by karisters**
Guys, we had problems with uncaught binary output in our project.

Cheers!

### CODE REVIEW

**Comment by endroid** [comment]
Nice, thank you!

**Comment by casperbiering** [comment]
Sorry to say, but you shouldn't call both "ob_end_flush" and "ob_get_clean". Both end the current buffer. Which causes PHP to the give following error: "PHP Notice:  ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in XXX on line YYY".

@endroid : Please undo this commit.

@karisters : You must have a bug somewhere else in your project :-(

**Comment by kukulich** [comment]
Yes, this commit is wrong. We get this error after update: `Cannot send header after HTTP headers have been sent (output started at vender/endroid/qrcode/src/QrCode.php:697`

**Comment by endroid** [comment]
@casperbiering and @kukulich You're right. This should be fixed in 1.6.4.

**Pull request merged**
