### PR TITLE
Add Center Logo Feature To QrCode Library, Hope It Is Useful :)

### PR DESCRIPTION
**Pull request by ice6**
I use the feature in my project, so I hope it is useful to others.
And I want to say thank you to the original author :)

### CODE REVIEW

**Comment by ice6** [comment]
thanks a lot for the merge and 1.6.5 release :+1: @endroid

**Comment by endroid** [comment]
You're welcome ;)

**Comment by IragiKNJ** [comment]
Where is the documentation on how to resolve missing dependencies and build the project.

**Comment by endroid** [comment]
Hi @IragiKNJ. Did you run composer as described in the readme? If so, can you please explain what dependencies you are missing? If this problem still occurs, please create a new issue so you reach more people who might be able to help you.

**Comment by IragiKNJ** [comment]
Hi @endroid, please allow me to make up a list for you. Thanks.

**Comment by IragiKNJ** [comment]
Good evening @endroid, 
Thanks for the help, but I was able to correct the missing libraries and references.
What is the correct ECCLevel for a QR Code that can allow me to pass a picture object to a bitmap variable and store it in a system's generated folder? My team and I have completed the construction of a system in MVC 5 ASP.NET C#. We have been successfully able to integrate the generator that you have produced to it, but it keeps generating an image that all our softwares - for image viewing - tag as invalid. I am suspecting the ECCLevel.

**Pull request merged**
