### PR TITLE
Let the logo have different image types

### PR DESCRIPTION
**Pull request by he426100**

### CODE REVIEW

**Comment by endroid** [comment]
Hi @he426100 thank you but something went wrong: all newlines were removed by your commit :)

I will manually update the relevant part of your PR when I return home from my vacation.

**Comment by coolbeatz71** [comment]
Hi, this library has the option of putting a logo in the center of the qrcode??? If yes, how Can i do it?

**Comment by endroid** [comment]
Hi @coolbeatz71 the class has a setLogo and setLogoSize method you can use. The image should be automatically centered. If not, please open a new issue. This one is about logo image types.

**Comment by Laurent3170** [comment]
```
$qrCode = new QrCode();
$qrCode->setLogo('/path/to/your/file');
```

**Comment by endroid** [comment]
Pull request code merged in 1.9.3.

**Pull request closed without merging**
