### PR TITLE
Refactor TWIG extension

### PR DESCRIPTION
**Pull request by Kolyunya**
Current implementation of the `qrcode_url` is inconsistent with the Symfony `url` function which returns an absolute URL to a resource. That is really misleading. Also it's inconvenient to concatenate request hostname manually to get an absolute URL to a QR code. 

I propose to refactor `qrcode_url` to return an absolute **URL** and to add a `qrcode_path` returning an absolute **path** to a QR code.

Seems like you are preparing a `2.0.0` release. That may be a perfect time to make this breaking change. Another option is to add a new function like `qrcode_absolute_url` without breaking the BC. I will adjust the PR if you decide to stick to the latter option.

### CODE REVIEW

**Comment by endroid** [comment]
Hi @Kolyunya. Good point and your solution looks good. I have made a lot of changes to the code base in the meanwhile so I decided to paste your code instead of merging the PR. Thank you!

**Comment by Kolyunya** [comment]
@endroid you are welcome! Haven't you committed it yet? Because I can't find it in the repository.

**Comment by endroid** [comment]
I did now. I still need to port some functionality but it's almost finished.

**Comment by Kolyunya** [comment]
Great job! Thank you! Looking forward for a stable release!

**Pull request closed without merging**
